### ISSUE TITLE
Publish (compiled) OpenApi Spec

### ISSUE THREAD

**Issue by WtfJoke** [phrase/openapi#183]
Hi there

Its great that you provide an open api spec. 

For my usecase howerver (generating an api client like you do) its a bit cumbersome  to do that, as I need to clone the complete git repo in order to access the open api spec.

It would be awesome when you would publish that "merged/compiled" spec somewhere in the web (on a github page or similar). 
So I would be able to curl/wget it from the web without cloning the repo. Or did I miss something and you have that spec already published somewhere?

What do you think?

**Comment by vermaxik** [comment]
Hi @WtfJoke,

we have the page with compiled specs available on https://developers.phrase.com/api/.

You can use it directly or extract compiled json.

**Comment by WtfJoke** [comment]
@vermaxik sorry to ask again. How can I access the api in `json` or `yaml` from the page you provided? 

In https://developers.phrase.com/api/ I only see the docs in html

**Comment by vermaxik** [comment]
> @vermaxik sorry to ask again. How can I access the api in `json` or `yaml` from the page you provided?
> 
> In https://developers.phrase.com/api/ I only see the docs in html

In page source -> https://developers.phrase.com/api/compiled.json

**Comment by WtfJoke** [comment]
Thank you :)
