### ISSUE TITLE
"List locales" API does not return configured fallback_locale

### ISSUE THREAD

**Issue by felixmagnus** [phrase/openapi#245]
Dear Phrase Team

We're trying to use the "List locales" API endpoint (documented here: https://developers.phrase.com/api/#get-/projects/-project_id-/locales) to get a list of all our configured locales in our project **including their `fallback_locale`**.

The API documentation says in the SCHEMA description at the bottom of the page that the  `fallback_locale` is included in the response payload, but in reality it is not.

Exemplary request - "List all locales":

![List all locales](https://user-images.githubusercontent.com/49987425/199674358-d8e562b1-127e-43da-b223-f899c4aba014.png)

When comparing this to the response payload of the "Get a single locale" API (see: https://developers.phrase.com/api/#get-/projects/-project_id-/locales/-id-), this one includes the `fallback_locale` correctly.

Exemplary request - "Get a single locale":

![Get a single locale](https://user-images.githubusercontent.com/49987425/199674590-b6e00848-2654-404f-8c53-1b158e67dcee.png)

It would be great if you could change your implementation of the "List all locales" endpoint to match the API documentation and **include the `fallback_locale`** in the response payload.

Please let me know if you need any further details to troubleshoot this issue.

Thanks

**Comment by docstun** [comment]
@felixmagnus the schema seems indeed off here, we'll investigate how that happened. Are you relying on the `fallback_locale` to be present in the list response?

**Comment by docstun** [comment]
@felixmagnus we added the `fallback_locale` to the list endpoint as well to comply with the specification. Sorry for this mistake!

**Comment by felixmagnus** [comment]
Hey @docstun 
Thanks a lot for the quick response and the fix!
