### ISSUE TITLE
"Translations" does not return the fallback content for untranslated keys

### ISSUE THREAD

**Issue by JAIRMG** [phrase/openapi#335]
Hi team

We are trying to get strings using `/projects/{project_id}/translations` API endpoint (documented [here](https://developers.phrase.com/api/#get-/projects/-project_id-/translations)) to get all translations for strings that have a common tag

This is working fine except for one thing, for strings that don't have translations we would expect to use the fallback content instead, however this is not part of the response, example

Request:

`https://api.phrase.com/v2/projects/:projectID/translations?page=1&per_page=100&q=tags:myTag`

Response:

```
[
    {
        "id": "xxxx",
        "content": "T&Cs",
        "unverified": false,
        "excluded": false,
        "plural_suffix": "",
        "key": {
            "id": "xxx",
            "name": "any_key_name",
            "plural": false,
            "data_type": "string",
            "tags": [
                "myTag",
                "anotherTag"
            ]
        },
        .
        .
        .
]
```

Is there a way to include the fallback content? 

Thanks!

**Comment by theSoenke** [comment]
Hi @JAIRMG, the translations endpoint itself does not include a fallback option. Instead I would suggest using the `download` endpoint: https://developers.phrase.com/api/#get-/projects/-project_id-/locales/-id-/download Downloading a whole locale at once will be a lot faster and it has the parameter `fallback_locale_id` and you will also be able to filter translations by tag

**Comment by JAIRMG** [comment]
Hi hi, thanks for the quick response.

The thing is that I want to download certain keys (let's say 10) in all languages available, but some of the languages for these keys have a fallback language, so, that's why I decided to use tags and pagination to download all these keys. With your suggestion I can't see how can I download all languages at once, this URL is asking for one locale id. Or I may be missing something?

**Comment by jablan** [comment]
@JAIRMG what's your use case?

**Comment by JAIRMG** [comment]
Hi @jablan, I would like to download a list of keys (20 to be exact) in all languages available. Some keys and just for certain languages they don't have translation but they have a fallback language. I started to use `/projects/{project_id}/translations` because that will avoid so many API calls, because I can use pagination, that is working perfectly fine, however, I noticed that the content for fallback language is missing, meaning that for those keys that are not translated the content is empty. I am testing @theSoenke suggestion but in that case I will need to make a lot of calls (AFAIK) to pull all languages, unless there is something that I am overlooking. I was wondering if translations endpoint can support including fallback option? So I can receive the fallback content for each key?

Thanks!

**Comment by jablan** [comment]
@JAIRMG I meant, what's your business use case, what do you do with 20 (random?) keys in all the languages?

**Comment by JAIRMG** [comment]
No no, definitely not random. I will use these keys to upload them to a internal server, they are not living directly in the iOS app

**Comment by jablan** [comment]
hey @JAIRMG not sure if you have solved your problem. another idea: you can combine locale download endpoint with a tag, so you download only a subset of translation keys that you need, and those with missing translations in target language will have values from fallback locale.
