### ISSUE TITLE
[BUG] phrase git_lab_sync history = ERROR: json: cannot unmarshal object into Go struct field GitlabSyncHistory.errors

### ISSUE THREAD

**Issue by horstmannmat** [phrase/openapi#372]
Is exactly the same issue with #362, but with another field, it was not caught before, cause it was failing first at the status field

When executing the `phrase git_lab_sync history` in the latest version of the phrase-cli, it raises an error message:
```bash
ERROR: json: cannot unmarshal object into Go struct field GitlabSyncHistory.errors of type string
```
This seems to be related to a type mismatch between the model returned by the API and the model that the CLI is expecting 
[gitlab_sync_history.yaml#L10-L13](https://github.com/phrase/openapi/blob/master/schemas/gitlab_sync_history.yaml#L10-L13)
```yaml
errors:
   type: array
   items:
       type: string
```
but the response is in fact an array of object

```json
"errors":[
   {
      "error":"GitSync::Gitlab::Importer::UploadFailed",
      "message":"Unauthorized"
   }
],
```

I will once again create an MR to fix this

**Comment by theSoenke** [comment]
This should now be fixed in version 2.8.4
