### ISSUE TITLE
Where's the spec?

### ISSUE THREAD

**Issue by felixdo** [phrase/openapi#681]
I can't use one of the predefined client libraries, but want to roll my own. Do you expose the actual openapi spec somewhere over https or do I have to clone this project, build it to get tmp/spec.yml and then consume that?

**Comment by felixdo** [comment]
Oh, nevermind, found it in one of the closed issues :)
https://developers.phrase.com/api/compiled.json

**Comment by jablan** [comment]
also: https://github.com/phrase/openapi/blob/master/doc/compiled.json
